#! /bin/sh

source panel_colors

source xcolors

num_mon=$(bspc query -M | wc -l)

## mark char:
## a b c d e f g h i j k l m n o p q r s t u v w x y z
## α β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ σ τ υ φ χ ψ ω
## Α Β Γ Δ Ε Ζ Η Θ Ι Κ Λ Μ Ν Ξ Ο Π Ρ Σ Τ Υ Φ Χ Ψ Ω

while read -r line ; do
    case $line in
        T*)
            # xtitle output
            #title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
            title="%{F${color['bt_magenta']}}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
            ;;
        L*)
            # loadavg
            load_mark="%{F${color['black']}}%{B${color['blue']}} λ %{B-}%{F-}"
            loadavg="$load_mark %{F${color['bt_blue']}}%{B$COLOR_DEFAULT_BG} ${line#?}  %{B-}%{F-}"
            ;;
        M*)
            # memory usage
            mem_mark="%{F${color['black']}}%{B${color['green']}} μ %{B-}%{F-}"
            mem="$mem_mark %{F${color['bt_green']}}%{B$COLOR_TITLE_BG} ${line#?}  %{B-}%{F-}"
            ;;
        S*)
            # datetime
            sys_mark="%{F${color['black']}}%{B${color['yellow']}} δ %{B-}%{F-}"
            sys="$sys_mark %{F${color['bt_yellow']}}%{B$COLOR_SYS_BG} ${line#?}  %{B-}%{F-}"
            ;;
        W*)
            # bspwm's state
            wm=
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    [mM]*)
                        case $item in
                            m*)
                                # monitor
                                FG=$COLOR_MONITOR_FG
                                BG=$COLOR_MONITOR_BG
                                on_focused_monitor=
                                ;;
                            M*)
                                # focused monitor
                                FG=$COLOR_FOCUSED_MONITOR_FG
                                BG=$COLOR_FOCUSED_MONITOR_BG
                                on_focused_monitor=1
                                ;;
                        esac
                        [ $num_mon -lt 2 ] && shift && continue
                        wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
                        ;;
                    [fFoOuU]*)
                        case $item in
                            f*)
                                # free desktop
                                FG=$COLOR_FREE_FG
                                BG=$COLOR_FREE_BG
                                UL=$BG
                                ;;
                            F*)
                                if [ "$on_focused_monitor" ] ; then
                                    # focused free desktop
                                    FG=$COLOR_FOCUSED_FREE_FG
                                    BG=$COLOR_FOCUSED_FREE_BG
                                    UL=$BG
                                else
                                    # active free desktop
                                    FG=$COLOR_FREE_FG
                                    BG=$COLOR_FREE_BG
                                    UL=$COLOR_FOCUSED_FREE_BG
                                fi
                                ;;
                            o*)
                                # occupied desktop
                                FG=$COLOR_OCCUPIED_FG
                                BG=$COLOR_OCCUPIED_BG
                                UL=$BG
                                ;;
                            O*)
                                if [ "$on_focused_monitor" ] ; then
                                    # focused occupied desktop
                                    FG=$COLOR_FOCUSED_OCCUPIED_FG
                                    BG=$COLOR_FOCUSED_OCCUPIED_BG
                                    UL=$BG
                                else
                                    # active occupied desktop
                                    FG=$COLOR_OCCUPIED_FG
                                    BG=$COLOR_OCCUPIED_BG
                                    UL=$COLOR_FOCUSED_OCCUPIED_BG
                                fi
                                ;;
                            u*)
                                # urgent desktop
                                FG=$COLOR_URGENT_FG
                                BG=$COLOR_URGENT_BG
                                UL=$BG
                                ;;
                            U*)
                                if [ "$on_focused_monitor" ] ; then
                                    # focused urgent desktop
                                    FG=$COLOR_FOCUSED_URGENT_FG
                                    BG=$COLOR_FOCUSED_URGENT_BG
                                    UL=$BG
                                else
                                    # active urgent desktop
                                    FG=$COLOR_URGENT_FG
                                    BG=$COLOR_URGENT_BG
                                    UL=$COLOR_FOCUSED_URGENT_BG
                                fi
                                ;;
                        esac
                        wm="${wm}%{F${FG}}%{B${BG}}%{U${UL}}%{+u}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}%{-u}"
                        ;;
                    [LTG]*)
                        # layout, state and flags
                        wm="${wm}%{F${color['bt_cyan']}}%{B$COLOR_STATE_BG} ${name} %{B-}%{F-}"
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "%{l}${wm}%{c}${title}%{r}${loadavg}${mem}${sys}"
done
