#!/bin/sh

# exec > >(tee /tmp/bspwm-login.log)
# exec 2>&1

ABS_PATH=$(realpath "$0")
DIR_PATH=$(dirname "$ABS_PATH")
DATETIME=$(date -d now +%s)

PANEL_HEIGHT=24
WINDOW_GAP=12

export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus

# https://wiki.archlinux.org/title/Bspwm#Problems_with_Java_applications
export _JAVA_AWT_WM_NONREPARENTING=1
# https://github.com/rawsh/dotfiles/blob/master/bspwm/.config/bspwm/bspwmrc
export _JAVA_OPTIONS='-Dsun.java2d.opengl=true'

[ -f /usr/bin/vmware-user-suid-wrapper ] && vmware-user-suid-wrapper &

# https://wiki.archlinux.org/index.php/xprofile
# [ -f /tmp/xprofile.lock ] || { [ -f $HOME/.xprofile ] && source $HOME/.xprofile; }
# [ "$DATETIME" -gt "$(date -d $(cat /tmp/bspwm.xprofile) +%s" ]

export PATH=$PATH:$DIR_PATH/panel
[ -e "$PANEL_FIFO" ] && bspc subscribe report > "$PANEL_FIFO" &
pgrep -f bspwm/panel > /dev/null && pkill -f bspwm/panel
panel &

pgrep -x sxhkd > /dev/null || sxhkd &

# ------------------------------------------------------------------

bspc monitor -d 1 2 3 4 5

# bspc config border_width                2
# bspc config window_gap                  12
# bspc config split_ratio                 0.52
# bspc config borderless_monocle          true
# bspc config gapless_monocle             true

source $DIR_PATH/panel/xcolors
bspc config active_border_color         "${color['bt_blue']}"
bspc config focused_border_color        "${color['bt_green']}"

bspc config border_width                2
bspc config window_gap                  "$WINDOW_GAP"
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true

bspc config focus_follows_pointer       true
bspc config pointer_modifier            mod4
# https://github.com/baskerville/bspwm/issues/678
bspc config pointer_action1             move
bspc config pointer_action2             resize_side
bspc config pointer_action3             resize_corner
#bspc config click_to_focus             none
# https://github.com/baskerville/bspwm/issues/1074
bspc config ignore_ewmh_focus           true

# man bspc
# pointer_modifier
#     Keyboard modifier used for moving or resizing windows. Accept the following values: shift, control, lock, mod1, mod2, mod3, mod4, mod5.
# pointer_action1, pointer_action2, pointer_action3
#     Action performed when pressing pointer_modifier + button<n>. Accept the following values: move, resize_side, resize_corner, focus, none.

# bspc monitor -d 1 2 3 4 5

# bspc monitor -d α β γ δ ε ζ
# α β γ δ ε ζ λ μ ν ξ ο π
# Α Β Γ Δ Ε Ζ Λ Μ Ν Ξ Ο Π

## RULE
## ----------------------------------------------------------------------------------------

## 查看窗口 class 属性命令：`xprop|grep -i class` 或 `bspc wm -d|python3 -m json.tool|less -i`

## BUGFIX: GUI emacs start up with float mode
## https://github.com/baskerville/bspwm/issues/551
bspc rule -a Emacs state=tiled
bspc rule -a Firefox desktop=^2 private=on follow=off focus=off
bspc rule -a Chromium private=on
bspc rule -a net-sourceforge-jnlp-runtime-Boot:* state=floating
bspc rule -a java-lang-Thread:* state=floating
bspc rule -a sun-awt-X11-XFramePeer:* state=floating

# bspc rule -a *:mupen64plus  state=floating

# https://github.com/siduck76/bspwm-dotfiles/blob/main/bspwmrc
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
# bspc config top_padding 20


# Turn bell off
xset b off
# Fix mouse cursor 'X'
xsetroot -cursor_name left_ptr &

# xsetroot -solid "#ffffff" &
xsetroot -mod 16 16 -bg "$(xrdb -query|awk '/\*color0/ {print $2}')" -fg "$(xrdb -query|awk '/\*color8/ {print $2}')" &

# xwininfo -root|awk '/Width|Height/{print $NF}'
mon_height=$(xwininfo -root|awk '/Height/{print $NF}')
mon_width=$(xwininfo -root|awk '/Width/{print $NF}')
# stalonetray --geometry 2x1+$(($mon_height - 24*2))-0 --transparent --kludges=force_icons_size --window-layer bottom



# stalonetray --transparent --grow-gravity E --geometry 2x1+$(($mon_width - $PANEL_HEIGHT*2 - $WINDOW_GAP))-$WINDOW_GAP --icon-gravity E --scrollbars horizontal --max-geometry 10x1 --kludges force_icons_size
stalonetray -t --grow-gravity E --geometry 2x1+$((1920 - 24*2 -12))-12
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $(xdo id -n stalonetray)


## Autostart Layout
## ----------------------------------------------------------------------------------------

## https://github.com/baskerville/bspwm/blob/master/tests/node/receptacle
## https://github.com/baskerville/bspwm/commit/e8aa679cd14fad3bdc89119c53d5c6eca6512bf0

# start_monitor=$(bspc wm -d|python3 -c "import sys, json; print(json.load(sys.stdin)['monitors'][0]['name'])")
# bspc monitor -f $start_monitor
# bspc desktop -f 1

### IT WORKS ------------------------------------------------------------------
#
#bspc node -i
#bspc node @/2 -p north -i
#
#bspc rule -a Firefox        -o node=@^1:^1:/1
#
#bspc rule -a Gnome-terminal -o node=@^1:^1:/2/1
##bspc rule -a Urxvt          -o node=@^1:^1:/2/1
##bspc rule -a konsole        -o node=@^1:^1:/2/1
#
#bspc rule -a Emacs          -o node=@^1:^1:/2/2
#
#firefox &
#/usr/bin/emacs & # emacs has 'alias' NEED full abosult path
#
#sleep 2
#gnome-terminal --hide-menubar -- tmux -2u new -s terminal &
##gnome-terminal --hide-menubar -- tmux -2u new -s terminal ss-local -v -c ~/ss/ss.json &
##konsole --hide-menubar -e 'tmux -2u new -s terminal ss-local -v -c ~/ss/ss.json' &
#
#sleep 2
#bspc node @^1:^1:/1   -z right  82 0  ## Firefox default tiled width: 1920/2 - 6 = 954 + 82 = 1036
#
#sleep 8
#bspc node @^1:^1:/2/1 -z bottom 0 -45 ## Emacs add 45px height

## Test ------------------------------------------------------------------

# bspc node @^1:^1:/ -i
# bspc node @^1:^1:/2 -p north -i

# bspc rule -a Emacs:emacs -o node=@^1:^1:/1
# bspc rule -a st-256color:st-256color -o node=@^1:^1:/2/1
# bspc rule -a URxvt:urxvt256c -o node=@^1:^1:/2/2

#urxvt256c -e bash -c "exec tmux new -s urxvt" &
#st -f "Bitstream Vera Sans Mono-11:antialias=1:autohint=0:hinting=1:hintstyle=1" -e tmux new -s st &
#emacs -Q &
#sleep 2

## IT WORKS ------------------------------------------------------------------

## 'layout.json' config created by 'extract_canvas' script under receptacles example
## https://github.com/baskerville/bspwm/tree/master/examples/receptacles
# bspc wm -l ~/layout.json

# bspc rule -a Emacs:emacs -o node=@^1:^1:/1 && emacs -Q &
# bspc rule -a st-256color:st-256color -o node=@^1:^1:/2/1 && st &
# bspc rule -a URxvt:urxvt256c -o node=@^1:^1:/2/2 && urxvt &

# { bspc node -i; for i in $(bspc query -N -n '.leaf.!window.local'); do bspc node $i -k; done; }

## END
