#! /bin/sh

ABS_PATH=$(realpath "$0")
DIR_PATH=$(dirname "$ABS_PATH")

export PATH=$PATH:$DIR_PATH/panel

sxhkd &
panel &

source $DIR_PATH/panel/xcolors

bspc config focus_follows_pointer true

bspc config active_border_color  "${color['bt_blue']}"
bspc config focused_border_color "${color['bt_green']}"
bspc config border_width         3
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d 1 2 3 4 5

# bspc monitor -d α β γ δ ε ζ
# α β γ δ ε ζ λ μ ν ξ ο π
# Α Β Γ Δ Ε Ζ Λ Μ Ν Ξ Ο Π

## RULE
## ----------------------------------------------------------------------------------------

## 查看窗口 class 属性命令：`xprop|grep -i class` 或 `bspc wm -d|python3 -m json.tool|less -i`

## BUGFIX: GUI emacs start up with float mode
## https://github.com/baskerville/bspwm/issues/551
bspc rule -a Emacs state=tiled
bspc rule -a Firefox private=on
bspc rule -a Chromium private=on

## Autostart Layout
## ----------------------------------------------------------------------------------------

## https://github.com/baskerville/bspwm/blob/master/tests/node/receptacle
## https://github.com/baskerville/bspwm/commit/e8aa679cd14fad3bdc89119c53d5c6eca6512bf0

# start_monitor=$(bspc wm -d|python3 -c "import sys, json; print(json.load(sys.stdin)['monitors'][0]['name'])")
# bspc monitor -f $start_monitor
# bspc desktop -f 1

## IT WORKS ------------------------------------------------------------------

bspc node -i
bspc node @/2 -p north -i

bspc rule -a Firefox        -o node=@^1:^1:/1
#bspc rule -a Urxvt         -o node=@^1:^1:/2/1
bspc rule -a Gnome-terminal -o node=@^1:^1:/2/1
bspc rule -a Emacs          -o node=@^1:^1:/2/2

firefox &
emacs &
sleep 2
gnome-terminal --hide-menubar -e "tmux -2u new -s terminal sslocal -c ~/ss.json" &

sleep 2
bspc node @^1:^1:/1   -z right  82 0  ## Firefox default tiled width: 1920/2 - 6 = 954 + 82 = 1036
sleep 8
bspc node @^1:^1:/2/1 -z bottom 0 -45 ## Emacs add 45px height

## Test ------------------------------------------------------------------

# bspc node @^1:^1:/ -i
# bspc node @^1:^1:/2 -p north -i

# bspc rule -a Emacs:emacs -o node=@^1:^1:/1
# bspc rule -a st-256color:st-256color -o node=@^1:^1:/2/1
# bspc rule -a URxvt:urxvt256c -o node=@^1:^1:/2/2

#urxvt256c -e bash -c "exec tmux new -s urxvt" &
#st -f "Bitstream Vera Sans Mono-11:antialias=1:autohint=0:hinting=1:hintstyle=1" -e tmux new -s st &
#emacs -Q &
#sleep 2

## IT WORKS ------------------------------------------------------------------

## 'layout.json' config created by 'extract_canvas' script under receptacles example
## https://github.com/baskerville/bspwm/tree/master/examples/receptacles
# bspc wm -l ~/layout.json

# bspc rule -a Emacs:emacs -o node=@^1:^1:/1 && emacs -Q &
# bspc rule -a st-256color:st-256color -o node=@^1:^1:/2/1 && st &
# bspc rule -a URxvt:urxvt256c -o node=@^1:^1:/2/2 && urxvt &

# { bspc node -i; for i in $(bspc query -N -n '.leaf.!window.local'); do bspc node $i -k; done; }

## END
