#! /bin/sh

ABS_PATH=$(realpath "$0")
DIR_PATH=$(dirname "$ABS_PATH")

export PATH=$PATH:$DIR_PATH/panel

sxhkd &
panel &

source $DIR_PATH/panel/xcolors

bspc config focus_follows_pointer true

#bspc config split_ratio         0.50

bspc config active_border_color  "${color['bt_blue']}"
bspc config focused_border_color "${color['bt_green']}"
bspc config border_width         3
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d 1 2 3 4 5

# bspc monitor -d α β γ δ ε ζ
# α β γ δ ε ζ λ μ ν ξ ο π
# Α Β Γ Δ Ε Ζ Λ Μ Ν Ξ Ο Π

## BUGFIX: GUI emacs start up with float mode
## https://github.com/baskerville/bspwm/issues/551
bspc rule -a Emacs state=tiled
bspc rule -a Firefox private=on
bspc rule -a Chromium private=on

## autostart layout
## https://github.com/baskerville/bspwm/blob/master/tests/node/receptacle
## https://github.com/baskerville/bspwm/commit/e8aa679cd14fad3bdc89119c53d5c6eca6512bf0

# start_monitor=$(bspc wm -d|python3 -c "import sys, json; print(json.load(sys.stdin)['monitors'][0]['name'])")
# bspc monitor -f $start_monitor
# bspc desktop -f 1

# bspc node -i
# #bspc node @/  -p east  -i
# bspc node @/2 -p north -i

# bspc rule -a st-256color -o node=@/1   && st -f "Bitstream Vera Sans Mono-11:antialias=1:autohint=0:hinting=1:hintstyle=1" -e tmux new -s st
# sleep 0.5s
# bspc rule -a Urxvt       -o node=@/2/1 && urxvt256c -e bash -c "exec tmux new -s urxvt"
# sleep 0.5s
# bspc rule -a Emacs       -o node=@/2/2 && emacs -Q

bspc node @^1:^1:/ -i
bspc node @^1:^1:/2 -p north -i

bspc rule -a Emacs:emacs -o node=@^1:^1:/1 && emacs -Q
bspc rule -a st-256color:st-256color -o node=@^1:^1:/2/1 && st
bspc rule -a URxvt:urxvt256c -o node=@^1:^1:/2/2 && urxvt

## END
